trigger:
- main

jobs:
- job: Phase_1
  pool:
   vmImage: macOS-12
  steps:
    - 
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: '7adb8d59-b247-4088-9032-7c8ceeabc1bf'
    definition: '3'
    buildVersionToDownload: 'latest'
    allowPartiallySucceededBuilds: true
    itemPattern: 'testingtest'
    targetPath: '$(Pipeline.Workspace)'