trigger:
- main

jobs:
- job: Phase_1
  pool:
   vmImage: macOS-12
  steps:
  - task: DownloadPipelineArtifact@2
    displayName: Download APK
    inputs:
     definition: 3
     itemPattern: dfgdfgdfgsfs
     allowFailedBuilds: false
     project: AnkitTestAutomation